name: Windows Workflow

on:
  push:
    branches:
    - dev-*
    tags:
    - release-v*.*

jobs:
  Build:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
      with:
        submodules: "recursive"
    - name: Setup node
      uses: actions/setup-node@v2.5.1    
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
    - name: Compile
      run: |
        cd armorpaint
        node armorcore/make -g direct3d11
        cd armorcore
        7z x v8\libraries\win32\release\v8_monolith.7z -ov8\libraries\win32\release -y
        git apply patch/window_handling.diff --directory=Kinc
        node Kinc/make -g direct3d11
    - name: Build
      run: |
        cd armorpaint
        cd armorcore
        msbuild build/ArmorPaint.sln /p:Configuration=Release /p:Platform=x64
    - name: Create Artifact
      run: |
        cd armorpaint
        cp -r armorcore/build/x64/Release/ArmorPaint.exe build/krom/ArmorPaint.exe
        cd build
        tree /f
        7z a ../armorpaint-${{github.ref_name}}-win_x64.zip *
    - name: Push Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: armorpaint-artifacts-win_x64
        path: armorpaint/armorpaint-${{github.ref_name}}-win_x64.zip
        if-no-files-found: error
  Release:
    runs-on: ubuntu-latest
    needs: Build
    permissions:
      contents: write
    steps:
    - name: Pull Artifact
      uses: actions/download-artifact@v2.1.0
      with:
        name: armorpaint-artifacts-win_x64
    - name: Release Artifact
      uses: softprops/action-gh-release@v1
      with:
        name: ${{github.ref_name}}
        files: armorpaint-*.zip